BLD: use C11 rather than C99 as the C standard version we target
In effect we were already using C11 for a long time, because that's
where `complex.h` and complex types became optional rather than
mandatory. Also, there were several places where we used typedef
redefinitions, which is a C11 feature, as indicated by build warnings
like these:

```
In file included from ../numpy/_core/src/multiarray/common.h:6:
../numpy/_core/include/numpy/ndarraytypes.h:308:31: warning: redefinition of typedef 'NpyAuxData' is a C11 feature [-Wtypedef-redefinition]
typedef struct NpyAuxData_tag NpyAuxData;
                              ^
../numpy/_core/src/umath/loops.h.src:37:31: note: previous definition is here
typedef struct NpyAuxData_tag NpyAuxData;
                              ^

In file included from ../numpy/_core/src/multiarray/array_method.h:14:
../numpy/_core/include/numpy/_dtype_api.h:108:3: warning: redefinition of typedef 'PyArrayMethod_Context' is a C11 feature [-Wtypedef-redefinition]
} PyArrayMethod_Context;
  ^
../numpy/_core/src/umath/loops.h.src:36:42: note: previous definition is here
typedef struct PyArrayMethod_Context_tag PyArrayMethod_Context;

```