TST: skip tests that checks for RecursionError under Pyodide/WASM
Failing after cibuildwheel update from 2.22.0 to 2.23.0

```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
  The cause of the fatal error was:
  RangeError: Maximum call stack size exceeded
```